### ISSUE TITLE
Feature Request: Add a selectable Date for Start analysis

### ISSUE THREAD

**Issue by edgardurao** [trekhleb/covid-19#25] opened 2020-03-31 08:40 UTC
Since the start dates of the infection is in most countries are different will it be possible to add a date for start selectable ?
That would make the analysis more friendly and conclusive.
Eventually a date for end would be a win too.

**Comment by kylegrover** [comment] 2020-04-01 19:31
potential duplicate of #6 ?

**Comment by abshakekumar** [comment] 2020-04-01 21:16
For the issue, i have opened a PR #30 
Please see https://github.com/trekhleb/covid-19/pull/30#issuecomment-607492238

**Comment by trekhleb** [comment] 2020-04-02 06:32
Closing this one in favour of https://github.com/trekhleb/covid-19/issues/6

**Closed as completed by trekhleb** 2020-04-02 06:32 UTC
